services:
  zsg_game:
    build: .
    env_file:
      - ./.env
    environment:
      - TZ=Australia/Brisbane
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - persisted_data:/app/data
    restart: unless-stopped

volumes:
  persisted_data: