version: '3.8'

services:
  bot:
    build: .
    env_file:
      - ./.env
    environment:
      - TZ=Australia/Brisbane
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - bot_data:/app/data
    restart: unless-stopped

volumes:
  bot_data: