name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "--- Starting SSH Deployment Script ---"
            echo "Current directory on remote: $(pwd)"
            echo "Changing directory to ~/bot..."
            cd ~/bot
            echo "Running git pull..."
            git pull
            echo "Running docker-compose up -d --build..."
            docker-compose up -d --build
            echo "--- Deployment Script Completed Successfully ---"